# Generated by Django 3.2.6 on 2021-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
