# Generated by Django 3.2.6 on 2021-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('New', 'Yangi'), ('False', 'Mavjud emas')], default='New', max_length=10),
        ),
    ]
