# Generated by Django 3.2.6 on 2021-08-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0002_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'Yangi'), ('True', 'Mavjud'), ('False', 'Mavjud emas')], default='New', max_length=10),
        ),
    ]
