# Generated by Django 3.2.6 on 2021-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('Read', "O'qilgan"), ('New', 'Yangi'), ('CLosed', 'Yopilgan')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=15),
        ),
    ]
